language: python

os:
  - linux

python:
  - 2.7
  - 3.6

sudo: false

install:
  - python -m pip install -r requirements.txt
  - python -m pip install numpy scipy no_version pytest bs4 pytest-cov

script:
  - python -c "import scooby; print(scooby.Report(core='numpy'))"
  - python -c "import scooby; print(scooby.Report(additional=['mock', 'foo']))"
  - python -c "import scooby; print(scooby.Report(additional=['foo',]))"
  - python -c "import scooby, mock; print(scooby.Report(additional=[mock,]))"
  - python -c "import scooby, mock; print(scooby.Report(additional=mock))"
  - python -c "import scooby, mock; print(scooby.Report(additional=mock)._repr_html_())"
  - python -c "import scooby; print(scooby.Report().listing(write=False))"
  # Test sorting
  - python -c "import scooby; print(scooby.Report(additional=['collections', 'foo', 'aaa'], sort=True))"
  # Test more complicated routines
  - python -m pytest -v --cov .

notifications:
  email:
    recipients:
      - info@pyvista.org
    on_success: never
    on_failure: never

deploy:
  - provider: pypi
    user: banesullivan
    distributions: sdist
    on:
      repo: banesullivan/scooby
      branch: master
      tags: true
      python: 3.6
    password: $PYPI_PASSWORD
