variables:
  ALLOW_PLOTTING: true
  SHELLOPTS: 'errexit:pipefail'

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'

jobs:


- job: LinuxTesing
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: |
      pip install -e .
    displayName: Install scooby

  - script: |
      pip install -r requirements_test.txt
      pip install pytest-azurepipelines
      pytest -v --cov pyvista --cov-report html
    displayName: Unit testing

  - script: |
      bash <(curl -s https://codecov.io/bash)
    displayName: 'Upload coverage to codecov.io'
    condition: eq(variables['python.version'], '3.7')

  - script: |
      pip install twine
      python setup.py sdist
      twine upload --skip-existing dist/scooby*.gz
    displayName: 'Upload to PyPi'
    condition: and(eq(variables['python.version'], '3.7'), contains(variables['Build.SourceBranch'], 'refs/tags/'))
    env:
      TWINE_USERNAME: $(twine.username)
      TWINE_PASSWORD: $(twine.password)
      TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"

  # don't run job on no-ci builds
  condition: not(contains(variables['System.PullRequest.SourceBranch'], 'no-ci'))
